name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
   action1:
    runs-on: ubuntu-latest
    steps:
     - name: url step
       run: |
        echo "url=${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_URL }}.dev." >> $GITHUB_OUTPUT
   post-deploy:
    needs: [action1]
    runs-on: ubuntu-latest
    steps:
        - run: echo "hola mundo"

