name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
   action1:
    runs-on: ubuntu-latest
    outputs:
        url: ${{ steps.set-url.outputs.url }}
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.5.0
      - name: url step
        id: set-url
        run: |
         echo "url=${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG_URL }}.dev." >> $GITHUB_OUTPUT
   post-deploy:
    needs: [action1]
    uses: FranciscoBodden/call-workflow/.github/workflows/call.yml@main
    with:
        URL: /api/ping